# Imagen base
FROM maven:3.8.1-jdk-11 AS build

WORKDIR /app-base/
COPY restaurantes/pom.xml .
RUN mvn -e -B dependency:resolve
COPY restaurantes/src ./src
RUN mvn install

WORKDIR /app/
COPY restaurantes-rest/pom.xml .
RUN mvn -e -B dependency:resolve
COPY restaurantes-rest/src ./src
RUN mvn clean package shade:shade

# Crear imagen para ejecutar la aplicación
FROM tomcat:9.0.58-jdk11
WORKDIR /usr/local/tomcat/webapps/
COPY --from=build /app/target/restaurantes-rest.war ./ROOT.war

EXPOSE 8080
CMD ["catalina.sh", "run"]