# Imagen base
FROM maven:3.8.1-jdk-8 AS build

WORKDIR /app-base/
COPY usuarios-pasarela/pom.xml .
RUN mvn -e -B dependency:resolve
COPY usuarios-pasarela/src ./src
RUN mvn install

WORKDIR /app/
COPY pasarela/pom.xml .
RUN mvn -e -B dependency:resolve
COPY pasarela/src ./src
RUN mvn package

# Crear imagen para ejecutar la aplicación
FROM openjdk:8-jre-slim
WORKDIR /app
COPY --from=build /app/target/pasarela-0.0.1-SNAPSHOT.jar ./pasarela.jar
EXPOSE 8090
ENTRYPOINT ["java", "-jar", "pasarela.jar"]