apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurantes-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurantes-rest
  template:
    metadata:
      labels:
        app: restaurantes-rest
    spec:
      containers:
      - name: restaurantes-rest
        image: angeltox/proyecto-arso-restaurantes-rest:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restaurantes-rest
spec:
  type: NodePort
  selector:
    app: restaurantes-rest
  ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080
